site_name: Project Documentation
site_url: https://example.com/

theme:
  name: material
  features:
    - navigation.tabs # Включаем табы через тему
  logo: assets/images/logo.svg
  favicon: assets/images/logo.svg

nav:
  - Overview: index.md
  - Templates: templates.md
  - Infrastructure:
      - 'Infra Docs': infra-docks/index.md # Ссылка на документацию infra-docks

plugins:
  - search
  - awesome-pages
  - jupyter
  - git-revision-date

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.details # Полезное расширение из infra-docks
  - attr_list # Полезное расширение из infra-docks
