# Конфигурация сайта
site_name: Project Docs
site_url: https://v-grand.github.io/docks/
repo_url: https://github.com/v-grand/docks
repo_name: v-grand/docks

# Тема оформления
theme:
  name: material
  language: ru
  logo: assets/logo.png # Предполагается, что логотип будет добавлен
  favicon: assets/logo.png # Предполагается, что логотип будет добавлен
  palette:
    scheme: default
  features:
    - navigation.tabs
    - navigation.top
  icon:
    repo: fontawesome/brands/github

# Навигация
nav:
  - 'Обзор': 'index.md'
  - 'Шаблоны': 'templates.md'
  - 'Документация по инфраструктуре': 'https://v-grand.github.io/infra-docks/en/'

# Расширения Markdown
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

# Плагины
plugins:
  - search
