site_name: Docks
repo_url: https://github.com/v-grand/docks

theme:
  name: material
  features:
    - navigation.tabs
  language: en
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    scheme: default
  icon:
    repo: fontawesome/brands/github

nav:
  - 'en':
    - 'Home': 'en/index.md'
    - 'Architecture': 'en/architecture.md'
    - 'Templates': 'en/templates.md'
  - 'ru':
    - 'Главная': 'ru/index.md'
    - 'Архитектура': 'ru/architecture.md'
    - 'Шаблоны': 'ru/templates.md'
  - 'pl':
    - 'Strona główna': 'pl/index.md'
    - 'Architektura': 'pl/architecture.md'
    - 'Szablony': 'pl/templates.md'

plugins:
  - search
  - i18n:
      default_language: en
      languages:
        en: English
        ru: Русский
        pl: Polski

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - toc:
      baselevel: 2
